CREATE TABLE submisisons (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    phonenumber INTEGER,
    email TEXT,
    resumesubmission TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);
