CREATE TABLE submissions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullname TEXT NOT NULL,
    phonenumber TEXT,
    email TEXT,
    resumelink TEXT NOT NULL,
    interestedposition TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);
